use Test::More qw(no_plan);
use_ok('UML::Model');
use_ok('UML::Item');
use_ok('UML::Attribute');
use_ok('UML::Class');
use_ok('UML::DataType');
use_ok('UML::Generalization');
use_ok('UML::Member');
use_ok('UML::Operation');
use_ok('UML::Package');
use_ok('UML::Parameter');
use_ok('UML::ReturnType');
use_ok('UML::TypeCache');
use_ok('UML::TypedThingy');
