use Test::More qw(no_plan);
use_ok('UML::Model');
use_ok('UML::Model::Item');
use_ok('UML::Model::Attribute');
use_ok('UML::Model::Class');
use_ok('UML::Model::DataType');
use_ok('UML::Model::Generalization');
use_ok('UML::Model::Member');
use_ok('UML::Model::Operation');
use_ok('UML::Model::Package');
use_ok('UML::Model::Parameter');
use_ok('UML::Model::ReturnType');
use_ok('UML::Model::TypeCache');
use_ok('UML::Model::TypedThingy');
